-- Trading Bot Database Schema (SQLite)
-- This schema tracks signals, orders, positions, and system state

-- Signals generated by the strategy
CREATE TABLE IF NOT EXISTS signals (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    timestamp TEXT NOT NULL,
    action TEXT NOT NULL,  -- 'sell_iron_condor' or 'no_trade'
    situation TEXT,  -- '1', '2', '3', '1B', '2B', '3B'
    reason TEXT,
    call_distance INTEGER,
    put_distance INTEGER,
    hedge_distance INTEGER,
    current_price REAL,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Orders placed with broker
CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id INTEGER,
    order_id TEXT UNIQUE NOT NULL,  -- Broker's order ID
    symbol TEXT NOT NULL,
    strike INTEGER,
    option_type TEXT,  -- 'CE' or 'PE'
    side TEXT NOT NULL,  -- 'BUY' or 'SELL'
    quantity INTEGER NOT NULL,
    order_type TEXT NOT NULL,  -- 'MARKET', 'LIMIT', etc.
    product_type TEXT NOT NULL,  -- 'INTRADAY', 'CARRYFORWARD'
    status TEXT NOT NULL,  -- 'PENDING', 'COMPLETE', 'REJECTED', 'CANCELLED'
    price REAL,
    average_price REAL,
    filled_quantity INTEGER DEFAULT 0,
    rejection_reason TEXT,
    placed_at TEXT DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (signal_id) REFERENCES signals(id)
);

-- Active positions
CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    symbol TEXT NOT NULL,
    strike INTEGER NOT NULL,
    option_type TEXT NOT NULL,  -- 'CE' or 'PE'
    side TEXT NOT NULL,  -- 'LONG' or 'SHORT'
    quantity INTEGER NOT NULL,
    entry_price REAL NOT NULL,
    current_price REAL,
    stop_loss REAL,
    target_price REAL,
    unrealized_pnl REAL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'OPEN',  -- 'OPEN', 'CLOSED'
    entry_time TEXT DEFAULT CURRENT_TIMESTAMP,
    exit_time TEXT,
    exit_price REAL
);

-- Completed trades (for P&L tracking and analytics)
CREATE TABLE IF NOT EXISTS trades (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    signal_id INTEGER,
    position_id INTEGER,
    strategy_name TEXT DEFAULT 'non_directional_strangle',
    entry_time TEXT NOT NULL,
    exit_time TEXT NOT NULL,
    duration_minutes INTEGER,
    entry_capital REAL NOT NULL,
    exit_capital REAL NOT NULL,
    gross_pnl REAL NOT NULL,
    commission REAL DEFAULT 0,
    net_pnl REAL NOT NULL,
    pnl_percentage REAL,
    max_drawdown REAL,
    exit_reason TEXT,  -- 'TARGET', 'STOP_LOSS', 'TIME_BASED', 'MANUAL'
    created_at TEXT DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (signal_id) REFERENCES signals(id),
    FOREIGN KEY (position_id) REFERENCES positions(id)
);

-- System state for crash recovery
CREATE TABLE IF NOT EXISTS system_state (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    state_key TEXT UNIQUE NOT NULL,
    state_value TEXT NOT NULL,
    updated_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Performance metrics (daily aggregates)
CREATE TABLE IF NOT EXISTS daily_metrics (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    date TEXT UNIQUE NOT NULL,
    total_signals INTEGER DEFAULT 0,
    total_trades INTEGER DEFAULT 0,
    winning_trades INTEGER DEFAULT 0,
    losing_trades INTEGER DEFAULT 0,
    gross_pnl REAL DEFAULT 0,
    commission REAL DEFAULT 0,
    net_pnl REAL DEFAULT 0,
    win_rate REAL DEFAULT 0,
    max_profit REAL DEFAULT 0,
    max_loss REAL DEFAULT 0,
    created_at TEXT DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_signals_timestamp ON signals(timestamp);
CREATE INDEX IF NOT EXISTS idx_orders_signal_id ON orders(signal_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_positions_status ON positions(status);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
CREATE INDEX IF NOT EXISTS idx_daily_metrics_date ON daily_metrics(date);
